name: BlockPartyPE
version: 1.3.0
api: [3.6.1, 3.6.0, 4.0.0]
main: ColorMatch\ColorMatch
author: CreeperFace, edited by Zeao.
description: BlockParty Mini-Game.

commands:
    cm:
        description: "ColorMatch command"

permissions:
    cm:
        description: "メインコマンド"
        default: op
        children:
            cm.command:
                description: "メインコマンドの権限"
                default: op
                children:
                    cm.command.help:
                        description: "ヘルプ"
                        default: true
                    cm.command.join:
                        description: "参加する"
                        default: true
                    cm.command.leave:
                        description: "離脱する "
                        default: true
                    cm.command.start:
                        description: "ブロックパーティーを開始する"
                        default: op
                    cm.command.stop:
                        description: "ブロックパーティーを停止する"
                        default: op
                    cm.command.kick:
                        description: "プレイヤーをブロックパーティーから追放する"
                        default: op
                    cm.command.lobby:
                        description: "ロビーに戻る"
                        default: true
                    cm.command.set:
                        description: "編集"
                        default: op
            cm.sign:
                description: "看板？"
                default: true
            cm.acces:
                description: "ブロックパーティーをさせる"
                default: true
